extends:
  - vazco/typescript

rules:
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-var-requires': off
  'eslint-comments/require-description': off
  'no-console': off
  'react/react-in-jsx-scope': off
  'react/display-name': off